---
- name: File module
  hosts: all
  become: true

  tasks:
  - name: creating a file
    file:
      path: /home/pranjal/createfile.txt
      state: absent
      owner: pranjal
      group: pranjal
      mode: u=rwx,g=rw,o=r

  - name: Creating folder
    file:
      path: /home/pranjal/myfolder
      state: directory
